### ISSUE TITLE
Issue while running this repo

### ISSUE THREAD

**Issue by ashishsahu2008** [grouparoo/app-example-docker#5]
Hello Team,

I am facing the following issue. Can you please help?

Steps followed:
1. Cloned the app-example-docker repo
2. cd app-example-docker
3. npm install
4. cp .env.example .env
5. docker-compose up

Following are the logs:
``` 
❯ docker-compose up
Starting grouparoo_redis ... done
Starting grouparoo_db    ... done
Starting app-example-docker_grouparoo-web_1 ... done
Starting app-example-docker_grouparoo-worker_1 ... done
Attaching to grouparoo_db, grouparoo_redis, app-example-docker_grouparoo-web_1, app-example-docker_grouparoo-worker_1
grouparoo_redis     | 1:C 29 Sep 2021 00:50:09.638 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
grouparoo_redis     | 1:C 29 Sep 2021 00:50:09.638 # Redis version=6.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
grouparoo_redis     | 1:C 29 Sep 2021 00:50:09.638 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
grouparoo_redis     | 1:M 29 Sep 2021 00:50:09.639 * monotonic clock: POSIX clock_gettime
grouparoo_db        |
grouparoo_db        | PostgreSQL Database directory appears to contain a database; Skipping initialization
grouparoo_db        |
grouparoo_db        | 2021-09-29 00:50:09.670 UTC [1] LOG:  starting PostgreSQL 13.4 (Debian 13.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
grouparoo_db        | 2021-09-29 00:50:09.670 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
grouparoo_db        | 2021-09-29 00:50:09.670 UTC [1] LOG:  listening on IPv6 address "::", port 5432
grouparoo_redis     | 1:M 29 Sep 2021 00:50:09.639 * Running mode=standalone, port=6379.
grouparoo_redis     | 1:M 29 Sep 2021 00:50:09.639 # Server initialized
grouparoo_db        | 2021-09-29 00:50:09.672 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
grouparoo_db        | 2021-09-29 00:50:09.676 UTC [26] LOG:  database system was interrupted; last known up at 2021-09-29 00:46:53 UTC
grouparoo_redis     | 1:M 29 Sep 2021 00:50:09.640 * Ready to accept connections
grouparoo_db        | 2021-09-29 00:50:09.877 UTC [26] LOG:  database system was not properly shut down; automatic recovery in progress
grouparoo_db        | 2021-09-29 00:50:09.879 UTC [26] LOG:  redo starts at 0/15CFE00
grouparoo_db        | 2021-09-29 00:50:09.896 UTC [26] LOG:  invalid record length at 0/178DD28: wanted 24, got 0
grouparoo_db        | 2021-09-29 00:50:09.896 UTC [26] LOG:  redo done at 0/178DC98
grouparoo_db        | 2021-09-29 00:50:09.950 UTC [1] LOG:  database system is ready to accept connections
grouparoo-web_1     | 2021-09-29T00:50:11.150Z - notice: Starting Grouparoo v0.6.3 on node.js v12.21.0
grouparoo-worker_1  | 2021-09-29T00:50:11.756Z - notice: Starting Grouparoo v0.6.3 on node.js v12.21.0
grouparoo-worker_1  | 2021-09-29T00:50:12.267Z - error: Error from Initializer name=environment file=/usr/src/node-app/node_modules/@grouparoo/core/dist/initializers/environment.js type=initialize stack=Grouparoo configuration error: PORT is not set and the web server is enabled.  Please ensure that all the required environment variables are set in your .env file or environment.  Learn more at https://www.grouparoo.com/docs/support/environment
grouparoo-worker_1  | 2021-09-29T00:50:12.268Z - crit: Cannot shut down @grouparoo/core, not running
grouparoo-web_1     | 2021-09-29T00:50:12.386Z - notice: pid: 1
grouparoo-web_1     | 2021-09-29T00:50:12.387Z - notice: environment: development
grouparoo-web_1     | 2021-09-29T00:50:12.387Z - info: *** Starting @grouparoo/core ***
grouparoo-web_1     | 2021-09-29T00:50:12.389Z - info: using path "/usr/src/node-app/files/development" for Grouparoo file storage
grouparoo-web_1     | 2021-09-29T00:50:12.390Z - info: active plugins: @grouparoo/core
grouparoo-web_1     | 2021-09-29T00:50:12.509Z - error: [ config ] A config object is missing an ID
grouparoo-web_1     | 2021-09-29T00:50:12.511Z - error: Error from Initializer name=codeConfig file=/usr/src/node-app/node_modules/@grouparoo/core/dist/initializers/codeConfig.js type=start stack=code config error
grouparoo-web_1     | 2021-09-29T00:50:12.512Z - notice: stopping process...
grouparoo-web_1     | 2021-09-29T00:50:12.617Z - notice: Stopping server: web
grouparoo-web_1     | 2021-09-29T00:50:12.618Z - notice: Stopping server: websocket
grouparoo-web_1     | 2021-09-29T00:50:12.740Z - notice: *** @grouparoo/core Stopped ***
grouparoo-worker_1  | 2021-09-29T00:50:14.709Z - notice: Starting Grouparoo v0.6.3 on node.js v12.21.0
grouparoo-worker_1  | 2021-09-29T00:50:15.237Z - error: Error from Initializer name=environment file=/usr/src/node-app/node_modules/@grouparoo/core/dist/initializers/environment.js type=initialize stack=Grouparoo configuration error: PORT is not set and the web server is enabled.  Please ensure that all the required environment variables are set in your .env file or environment.  Learn more at https://www.grouparoo.com/docs/support/environment
grouparoo-worker_1  | 2021-09-29T00:50:15.238Z - crit: Cannot shut down @grouparoo/core, not running
grouparoo-web_1     | 2021-09-29T00:50:15.603Z - notice: Starting Grouparoo v0.6.3 on node.js v12.21.0
app-example-docker_grouparoo-worker_1 exited with code 1
grouparoo-web_1     | 2021-09-29T00:50:16.799Z - notice: pid: 1
grouparoo-web_1     | 2021-09-29T00:50:16.800Z - notice: environment: development
grouparoo-web_1     | 2021-09-29T00:50:16.800Z - info: *** Starting @grouparoo/core ***
grouparoo-web_1     | 2021-09-29T00:50:16.802Z - info: using path "/usr/src/node-app/files/development" for Grouparoo file storage
grouparoo-web_1     | 2021-09-29T00:50:16.803Z - info: active plugins: @grouparoo/core
grouparoo-web_1     | 2021-09-29T00:50:16.921Z - error: [ config ] A config object is missing an ID
grouparoo-web_1     | 2021-09-29T00:50:16.923Z - error: Error from Initializer name=codeConfig file=/usr/src/node-app/node_modules/@grouparoo/core/dist/initializers/codeConfig.js type=start stack=code config error
grouparoo-web_1     | 2021-09-29T00:50:16.924Z - notice: stopping process...
grouparoo-web_1     | 2021-09-29T00:50:17.026Z - notice: Stopping server: web
grouparoo-web_1     | 2021-09-29T00:50:17.027Z - notice: Stopping server: websocket
grouparoo-web_1     | 2021-09-29T00:50:17.146Z - notice: *** @grouparoo/core Stopped ***
```

**Comment by evantahler** [comment]
Thanks for the bug report!

I've followed the steps you've listed, but the app boots up OK for me.  There's a few interesting notes in your logs that indicate that perhaps you've modified this directory in some way:

* The worker process is trying to start the web server.  The worker process should [not have the web server enabled](https://github.com/grouparoo/app-example-docker/blob/main/docker-compose.yml#L49)

```
grouparoo-worker_1  | 2021-09-29T00:50:12.267Z - error: Error from Initializer name=environment file=/usr/src/node-app/node_modules/@grouparoo/core/dist/initializers/environment.js type=initialize stack=Grouparoo configuration error: PORT is not set and the web server is enabled.  Please ensure that all the required environment variables are set in your .env file or environment.  Learn more at https://www.grouparoo.com/docs/support/environment
```

* You may have tried to inject a code config directory into this repo (or have a "config") directory. 

```
grouparoo-web_1     | 2021-09-29T00:50:12.511Z - error: Error from Initializer name=codeConfig file=/usr/src/node-app/node_modules/@grouparoo/core/dist/initializers/codeConfig.js type=start stack=code config error
```

Can you share if you've modified anything?

**Comment by ashishsahu2008** [comment]
Hi @evantahler 
Thank you for your quick reply.

I have not made any changes locally. I am running the project as it is after cloning from the git repo. Here is the output of `git status`:
```
❯ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
```

Also, I have checked that the worker process does not have the web server enabled. Following is my `docker-compose.yml`.
```
version: "3.1"
services:
  redis:
    container_name: grouparoo_redis
    image: redis
    restart: always
    networks:
      - grouparoo_backend

  db:
    container_name: grouparoo_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: grouparoo_docker
    networks:
      - grouparoo_backend
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  grouparoo-web:
    build: ./
    image: grouparoo/local-image
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "production"
      PORT: 3000
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:password@db:5432/grouparoo_docker
      WEB_SERVER: "true"
      WORKERS: 0
      SERVER_TOKEN: "default-server-token"
    depends_on:
      - db
      - redis
    networks:
      - grouparoo_frontend
      - grouparoo_backend

  grouparoo-worker:
    image: grouparoo/local-image
    restart: always
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql://postgres:password@db:5432/grouparoo_docker
      WEB_SERVER: "false"
      WORKERS: 5
      SERVER_TOKEN: "default-server-token"
    depends_on:
      - db
      - redis
      - grouparoo-web
    networks:
      - grouparoo_frontend
      - grouparoo_backend

networks:
  grouparoo_frontend:
  grouparoo_backend:

volumes:
  postgres-data:
```
